// Which weapons and armor drop from which encounter, for raids and dungeons (the Assistant's "Where the loot
// drops" section). Bungie's data doesn't say this (collectibles only name the whole activity), so it comes from
// the owner's own compiled sheet (D2_Raid_Dungeon_Loot.xlsx, Sep 2026). Keys are the activity names in
// lib/rotations.js. Weapon names must match the collectibles' names (case, curly quotes and punctuation are
// ignored). `armor` is which slots drop; `shared` marks activities whose legendaries use one pool for every
// encounter; `exotic.from` is the encounter or quest that awards it; `modes` holds extra difficulties with their
// own pools (shown as separate tables); `aliases` lets a non-raid seal find its table by name.
export const LOOT_TABLES = {
  // From the owner's screenshots (Sep 2026). The first three encounters can be done in any order. Normal and
  // Epic have different pools, so the Assistant shows both.
  "The Desert Perpetual": {
    encounters: [
      { name: "Agraios", weapons: ["Antedate", "Lance Ephemeral", "Intercalary"], armor: "Leg Armor" },
      { name: "Iatros", weapons: ["Finite Maybe", "The When and Where"], armor: "Chest Armor, Helmet" },
      { name: "Epoptes", weapons: ["Opaque Hourglass"], armor: "Leg Armor, Class Item, Gauntlets" },
    ],
    modes: {
      Epic: [
        { name: "Agraios", weapons: ["Finite Maybe", "The Ever-Present", "The When and Where"], armor: "Gauntlets, Chest Armor" },
        { name: "Iatros", weapons: ["Opaque Hourglass", "Starscape Null", "Lance Ephemeral"], armor: "Chest Armor, Helmet" },
        { name: "Epoptes", weapons: ["The When and Where", "Cusp Sempiternal"], armor: "Gauntlets, Leg Armor" },
      ],
    },
    exotic: { name: "Whirling Ovation", from: "Koregos, the final encounter" },
  },
  // From the owner's Equilibrium infographic (Sep 2026).
  Equilibrium: {
    encounters: [
      { name: "Harvester", weapons: ["Zealous Ideal", "Voltaic Shade", "Bitter End"], armor: "Gauntlets, Chest Armor, Leg Armor" },
      { name: "Harrow", weapons: ["Conspiracy Honed", "Voltaic Shade", "Bitter End"], armor: "Helmet, Gauntlets, Class Item" },
      {
        name: "Sere",
        weapons: ["High Tyrant", "Conspiracy Honed", "Voltaic Shade", "Sullen Claw", "Bitter End", "Zealous Ideal"],
        armor: "Chest Armor, Leg Armor, Class Item",
        note: "Can award any Equilibrium weapon",
      },
    ],
    exotic: { name: "Heirloom", from: "Sere (random drop)", note: "Catalyst from The Way Between quest" },
  },
  // Pantheon 2.0 (Monument of Triumph), from the owner's screenshots (Sep 2026). Not a raid, so it's found by
  // the seal's name instead (`aliases`). Armor (Pantheon Resplendent) can drop from any boss.
  Pantheon: {
    aliases: ["Pantheon", "Godslayer", "Monument of Triumph"],
    encounters: [
      { name: "Argos, Planetary Core", weapons: ["Alone as a God"], armor: "Any armor" },
      { name: "Warpriest", weapons: ["Zaouli's Bane"], armor: "Any armor" },
      { name: "Gahlran, the Sorrow-Bearer", weapons: ["Bane of Sorrow"], armor: "Any armor" },
      { name: "Consecrated Mind, Sol Inherent", weapons: ["Reckless Oracle"], armor: "Any armor" },
      { name: "Emperor Calus", weapons: ["Alone as a God"], armor: "Any armor" },
      { name: "Morgeth, the Spirekeeper", weapons: ["Chattering Bone"], armor: "Any armor" },
      { name: "Insurrection Prime, Kell's Scourge", weapons: ["Threat Level"], armor: "Any armor" },
    ],
  },
  "Root of Nightmares": {
    encounters: [
      { name: "Cataclysm", weapons: ["Nessa's Oblation", "Briar's Contempt", "Koraxis's Distress"], armor: "Helmet, Gauntlets, Chest Armor" },
      { name: "Scission", weapons: ["Nessa's Oblation", "Acasia's Dejection", "Mykel's Reverence", "Koraxis's Distress"], armor: "Gauntlets, Chest Armor, Leg Armor" },
      { name: "Macrocosm", weapons: ["Rufus's Fury", "Acasia's Dejection", "Mykel's Reverence", "Koraxis's Distress"], armor: "Chest Armor, Leg Armor, Class Item" },
      { name: "Nezarec", weapons: ["Nessa's Oblation", "Briar's Contempt", "Koraxis's Distress", "Acasia's Dejection", "Mykel's Reverence", "Rufus's Fury"], armor: "Helmet, Leg Armor, Class Item", note: "Can award any Root of Nightmares weapon" },
    ],
    exotic: { name: "Conditional Finality", from: "Nezarec" },
  },
  "Garden of Salvation": {
    encounters: [
      { name: "Evade the Consecrated Mind", weapons: ["Zealot's Reward", "Accrued Redemption"], armor: "Leg Armor" },
      { name: "Summon the Consecrated Mind", weapons: ["Prophet of Doom", "Reckless Oracle"], armor: "Gauntlets" },
      { name: "Defeat the Consecrated Mind", weapons: ["Ancient Gospel", "Sacred Provenance"], armor: "Chest Armor" },
      { name: "Defeat the Sanctified Mind", weapons: ["Omniscient Eye"], armor: "Helmet, Class Item" },
    ],
    exotic: { name: "Divinity", from: "Divine Fragmentation quest and raid puzzles" },
  },
  "Deep Stone Crypt": {
    encounters: [
      { name: "Crypt Security", weapons: ["Trustee"], armor: "Gauntlets, Leg Armor, Class Item" },
      { name: "Atraks-1", weapons: ["Heritage", "Succession"], armor: "Gauntlets, Leg Armor, Class Item" },
      { name: "Descent", weapons: ["Heritage", "Posterity"], armor: "Gauntlets, Chest Armor, Class Item" },
      { name: "Taniks, the Abomination", weapons: ["Commemoration", "Bequest"], armor: "Helmet, Chest Armor, Leg Armor" },
    ],
    exotic: { name: "Eyes of Tomorrow", from: "Taniks, the Abomination" },
  },
  "Crota's End": {
    encounters: [
      { name: "The Abyss", weapons: ["Song of Ir Yût", "Abyss Defiant", "Fang of Ir Yût"], armor: "Helmet, Gauntlets, Chest Armor" },
      { name: "The Bridge", weapons: ["Swordbreaker", "Oversoul Edict", "Fang of Ir Yût"], armor: "Gauntlets, Chest Armor, Leg Armor" },
      { name: "Ir Yût, the Deathsinger", weapons: ["Song of Ir Yût", "Oversoul Edict", "Word of Crota"], armor: "Chest Armor, Leg Armor, Class Item" },
      { name: "Crota, Son of Oryx", weapons: ["Swordbreaker", "Abyss Defiant", "Word of Crota"], armor: "Helmet, Leg Armor, Class Item" },
    ],
    exotic: { name: "Necrochasm", from: "Bottomless Pit quest" },
  },
  "Last Wish": {
    encounters: [
      { name: "Shared raid pool", weapons: ["Nation of Beasts", "The Supremacy", "Apex Predator", "Chattering Bone", "Transfiguration", "Tyranny of Heaven", "Age-Old Bond", "Techeun Force"], armor: "Great Hunt armor set", shared: true, note: "Legendary drops use a shared raid pool" },
    ],
    exotic: { name: "One Thousand Voices", from: "Final reward chest" },
  },
  "King's Fall": {
    encounters: [
      { name: "Gate", weapons: ["Doom of Chelchis", "Qullim's Terminus"], armor: "Class Item" },
      { name: "Basilica", weapons: ["Doom of Chelchis", "Qullim's Terminus"], armor: "Chest Armor, Leg Armor" },
      { name: "Warpriest", weapons: ["Smite of Merain", "Defiance of Yasmin", "Qullim's Terminus"], armor: "Gauntlets, Chest Armor" },
      { name: "Golgoroth", weapons: ["Doom of Chelchis", "Zaouli's Bane", "Midha's Reckoning", "Qullim's Terminus"], armor: "Helmet, Leg Armor" },
      { name: "The Daughters", weapons: ["Doom of Chelchis", "Smite of Merain", "Zaouli's Bane", "Defiance of Yasmin"], armor: "Gauntlets, Chest Armor" },
      { name: "Oryx, the Taken King", weapons: ["Doom of Chelchis", "Qullim's Terminus", "Smite of Merain", "Defiance of Yasmin", "Zaouli's Bane", "Midha's Reckoning"], armor: "Helmet, Gauntlets", note: "Can award any King's Fall weapon" },
    ],
    exotic: { name: "Touch of Malice", from: "Oryx, the Taken King" },
  },
  "Vault of Glass": {
    encounters: [
      { name: "Confluxes", weapons: ["Found Verdict", "Vision of Confluence", "Corrective Measure"], armor: "Gauntlets, Class Item" },
      { name: "Oracles", weapons: ["Found Verdict", "Vision of Confluence", "Praedyth's Revenge"], armor: "Gauntlets, Leg Armor" },
      { name: "Templar", weapons: ["Fatebringer", "Vision of Confluence", "Corrective Measure"], armor: "Gauntlets, Chest Armor" },
      { name: "Gatekeepers", weapons: ["Found Verdict", "Fatebringer", "Hezen Vengeance"], armor: "Helmet, Leg Armor" },
      { name: "Atheon", weapons: ["Praedyth's Revenge", "Corrective Measure", "Hezen Vengeance"], armor: "Helmet, Chest Armor" },
    ],
    exotic: { name: "Vex Mythoclast", from: "Atheon" },
  },
  "Salvation's Edge": {
    encounters: [
      { name: "Substratum", weapons: ["Imminence", "Non-Denouement", "Nullify"], armor: "Gauntlets, Chest Armor" },
      { name: "Herald of Finality", weapons: ["Imminence", "Forthcoming Deviance", "Non-Denouement"], armor: "Helmet, Class Item" },
      { name: "Repository", weapons: ["Critical Anomaly", "Forthcoming Deviance", "Nullify"], armor: "Gauntlets, Class Item" },
      { name: "Verity", weapons: ["Imminence", "Summum Bonum", "Non-Denouement"], armor: "Chest Armor, Leg Armor" },
      { name: "The Witness", weapons: ["Critical Anomaly", "Summum Bonum", "Nullify"], armor: "Helmet, Leg Armor" },
    ],
    exotic: { name: "Euphony", from: "The Witness" },
  },
  "Vow of the Disciple": {
    encounters: [
      { name: "Acquisition", weapons: ["Submission", "Deliverance", "Cataclysmic"], armor: "Helmet, Chest Armor, Leg Armor" },
      { name: "The Caretaker", weapons: ["Submission", "Insidious", "Cataclysmic", "Forbearance"], armor: "Helmet, Gauntlets, Class Item" },
      { name: "Exhibition", weapons: ["Submission", "Deliverance"], armor: "Helmet, Chest Armor, Leg Armor" },
      { name: "Rhulk", weapons: ["Insidious", "Forbearance", "Lubrae's Ruin"], armor: "Helmet, Gauntlets, Class Item" },
    ],
    exotic: { name: "Collective Obligation", from: "Rhulk" },
  },
  "Spire of the Watcher": {
    encounters: [
      { name: "Ascend the Spire", weapons: ["Long Arm", "Terminus Horizon"], armor: "Helmet, Gauntlets, Leg Armor" },
      { name: "Silence the Spire", weapons: ["Terminus Horizon"], armor: "Gauntlets, Chest Armor, Class Item" },
      { name: "Persys, Primordial Ruin", weapons: ["Liminal Vigil", "Wilderflight", "Long Arm", "Terminus Horizon"], armor: "All armor", note: "Can award items from earlier encounters" },
    ],
    exotic: { name: "Hierarchy of Needs", from: "Persys, Primordial Ruin" },
  },
  "Sundered Doctrine": {
    encounters: [
      { name: "Solve the Riddle", weapons: ["Unloved", "Unsworn", "Unworthy"], armor: "Helmet, Gauntlets, Leg Armor" },
      { name: "Zoetic Lockset", weapons: ["Unloved", "Unsworn", "Unvoiced"], armor: "Helmet, Gauntlets, Leg Armor" },
      { name: "Kerrev, the Erased", weapons: ["Unloved", "Unsworn", "Unworthy", "Unvoiced"], armor: "All armor", note: "Can award any Sundered Doctrine weapon; class item tied to The Drowning Labyrinth quest or Master clears" },
    ],
    exotic: { name: "Finality's Auger", from: "Kerrev, the Erased", note: "Catalyst tied to The Drowning Labyrinth quest" },
  },
  "Ghosts of the Deep": {
    encounters: [
      { name: "Hive Ritual Disrupted", weapons: ["New Pacific Epitaph", "Cold Comfort", "No Survivors"], armor: "Helmet, Gauntlets, Leg Armor" },
      { name: "Ecthar, the Shield of Savathûn", weapons: ["Greasy Luck", "Cold Comfort", "No Survivors"], armor: "Gauntlets, Chest Armor, Class Item" },
      { name: "Simmumah ur-Nokru", weapons: ["New Pacific Epitaph", "Cold Comfort", "No Survivors", "Greasy Luck"], armor: "All armor", note: "Can award any Ghosts of the Deep weapon" },
    ],
    exotic: { name: "The Navigator", from: "Simmumah ur-Nokru" },
  },
  "The Shattered Throne": {
    encounters: [
      { name: "Shared dungeon pool", weapons: ["Vulpecula", "Chrysura Melo", "Fractethyst", "Canis Major"], armor: "Techeun's Regalia armor set", shared: true, note: "Legendary drops use a shared dungeon pool" },
    ],
    exotic: { name: "Wish-Ender", from: "Wish-Ender quest" },
  },
  "Vesper's Host": {
    encounters: [
      { name: "Activation", weapons: ["VS Chill Inhibitor", "VS Gravitic Arrest", "VS Velocity Baton"], armor: "Gauntlets, Chest Armor, Leg Armor" },
      { name: "Raneiks Unified", weapons: ["VS Chill Inhibitor", "VS Gravitic Arrest", "VS Pyroelectric Propellant"], armor: "Helmet, Gauntlets, Leg Armor" },
      { name: "The Corrupted Puppeteer", weapons: ["VS Chill Inhibitor", "VS Gravitic Arrest", "VS Velocity Baton", "VS Pyroelectric Propellant"], armor: "Helmet, Chest Armor, Leg Armor", note: "Can award any Vesper's Host weapon; class item earned through the Rogue Network quest" },
    ],
    exotic: { name: "Ice Breaker", from: "The Corrupted Puppeteer", note: "Catalyst tied to the dungeon's secret puzzle" },
  },
  "Duality": {
    encounters: [
      { name: "Nightmare of Gahlran", weapons: ["Lingering Dread", "The Epicurean"], armor: "Helmet, Gauntlets, Leg Armor" },
      { name: "Unlock the Vault", weapons: ["Stormchaser", "Unforgiven"], armor: "Gauntlets, Chest Armor, Class Item" },
      { name: "Nightmare of Caiatl", weapons: ["New Purpose", "Fixed Odds"], armor: "All armor" },
    ],
    exotic: { name: "Heartshadow", from: "Nightmare of Caiatl" },
  },
  "Warlord's Ruin": {
    encounters: [
      { name: "Rathil, First Broken Knight", weapons: ["Indebted Kindness", "Vengeful Whisper", "Dragoncult Sickle"], armor: "Helmet, Gauntlets, Leg Armor" },
      { name: "Locus of Wailing Grief", weapons: ["Indebted Kindness", "Vengeful Whisper", "Naeem's Lance"], armor: "Gauntlets, Chest Armor, Class Item" },
      { name: "Hefnd's Vengeance", weapons: ["Indebted Kindness", "Vengeful Whisper", "Dragoncult Sickle", "Naeem's Lance"], armor: "All armor", note: "Can award any Warlord's Ruin weapon" },
    ],
    exotic: { name: "Buried Bloodline", from: "Hefnd's Vengeance" },
  },
  "Pit of Heresy": {
    encounters: [
      { name: "Shared dungeon pool", weapons: ["Psychopomp", "Adamantite", "Refusal of the Call", "Eyes Unveiled"], armor: "Apostate's Blade armor set", shared: true, note: "Legendary drops use a shared dungeon pool" },
    ],
    exotic: { name: "Xenophage", from: "The Journey quest" },
  },
  "Prophecy": {
    encounters: [
      { name: "Phalanx Echo", weapons: ["Relentless", "Prosecutor"], armor: "Leg Armor, Class Item" },
      { name: "Hexahedron", weapons: ["A Sudden Death", "Adjudicator"], armor: "Gauntlets" },
      { name: "Kell Echo", weapons: ["Darkest Before", "Judgment", "Prosecutor"], armor: "All armor" },
    ],
  },
  "Grasp of Avarice": {
    encounters: [
      { name: "Phry'zhia, the Insatiable", weapons: ["Matador 64"], armor: "Leg Armor, Class Item" },
      { name: "Fallen Shield", weapons: ["Hero of Ages"], armor: "Gauntlets, Chest Armor" },
      { name: "Avarokk, the Covetous", weapons: ["Eyasluna", "1000 Yard Stare", "Matador 64", "Hero of Ages"], armor: "All armor", note: "Can award items from earlier encounters" },
    ],
    exotic: { name: "Gjallarhorn", from: "And Out Fly the Wolves quest" },
  },
};

// Weapon type and element, shown when hovering an item (from the same sheet).
export const WEAPON_KINDS = {
  // The Desert Perpetual, Equilibrium and Pantheon (owner's screenshots; Equilibrium's elements weren't legible).
  Antedate: "Submachine Gun · Arc",
  "Lance Ephemeral": "Sniper Rifle · Strand",
  Intercalary: "Auto Rifle · Stasis",
  "Finite Maybe": "Fusion Rifle · Solar",
  "The When and Where": "Rocket Launcher · Stasis",
  "Opaque Hourglass": "Combat Bow · Arc",
  "The Ever-Present": "Grenade Launcher · Strand",
  "Starscape Null": "Shotgun · Solar",
  "Cusp Sempiternal": "Auto Rifle · Void",
  "Whirling Ovation": "Rocket Launcher · Strand",
  "Zealous Ideal": "Auto Rifle",
  "Voltaic Shade": "Scout Rifle",
  "Bitter End": "Machine Gun",
  "Conspiracy Honed": "Sniper Rifle",
  "High Tyrant": "Pulse Rifle",
  "Sullen Claw": "Sword",
  Heirloom: "Combat Bow",
  "Alone as a God": "Sniper Rifle · Kinetic",
  "Bane of Sorrow": "Machine Gun · Void",
  "Threat Level": "Shotgun · Kinetic",
  "1000 Yard Stare": "Sniper Rifle · Void",
  "A Sudden Death": "Shotgun · Void",
  "Abyss Defiant": "Auto Rifle · Solar",
  "Acasia's Dejection": "Trace Rifle · Solar",
  "Accrued Redemption": "Combat Bow · Kinetic",
  "Adamantite": "Auto Rifle · Strand",
  "Adjudicator": "Submachine Gun · Kinetic",
  "Age-Old Bond": "Auto Rifle · Void",
  "Ancient Gospel": "Hand Cannon · Void",
  "Apex Predator": "Rocket Launcher",
  "Bequest": "Sword · Arc",
  "Briar's Contempt": "Linear Fusion Rifle · Solar",
  "Buried Bloodline": "Sidearm · Void",
  "Canis Major": "Grenade Launcher",
  "Cataclysmic": "Linear Fusion Rifle · Solar",
  "Chattering Bone": "Pulse Rifle · Kinetic",
  "Chrysura Melo": "Auto Rifle · Arc",
  "Cold Comfort": "Rocket Launcher · Stasis",
  "Collective Obligation": "Pulse Rifle · Void",
  "Commemoration": "Machine Gun · Void",
  "Conditional Finality": "Shotgun · Stasis",
  "Corrective Measure": "Machine Gun · Void",
  "Critical Anomaly": "Sniper Rifle · Stasis",
  "Darkest Before": "Pulse Rifle · Solar",
  "Defiance of Yasmin": "Sniper Rifle · Kinetic",
  "Deliverance": "Fusion Rifle · Stasis",
  "Divinity": "Trace Rifle · Arc",
  "Doom of Chelchis": "Scout Rifle · Void",
  "Dragoncult Sickle": "Sword · Strand",
  "Euphony": "Linear Fusion Rifle · Strand",
  "Eyasluna": "Hand Cannon · Stasis",
  "Eyes Unveiled": "Linear Fusion Rifle",
  "Eyes of Tomorrow": "Rocket Launcher · Solar",
  "Fang of Ir Yût": "Scout Rifle · Strand",
  "Fatebringer": "Hand Cannon · Kinetic",
  "Finality's Auger": "Linear Fusion Rifle · Solar",
  "Fixed Odds": "Machine Gun · Solar",
  "Forbearance": "Grenade Launcher · Arc",
  "Forthcoming Deviance": "Glaive · Void",
  "Found Verdict": "Shotgun · Arc",
  "Fractethyst": "Shotgun",
  "Gjallarhorn": "Rocket Launcher · Solar",
  "Greasy Luck": "Glaive · Solar",
  "Heartshadow": "Sword · Void",
  "Heritage": "Shotgun · Kinetic",
  "Hero of Ages": "Sword · Arc",
  "Hezen Vengeance": "Rocket Launcher · Solar",
  "Hierarchy of Needs": "Combat Bow · Solar",
  "Ice Breaker": "Sniper Rifle · Solar",
  "Imminence": "Submachine Gun · Strand",
  "Indebted Kindness": "Sidearm · Arc",
  "Insidious": "Pulse Rifle · Arc",
  "Judgment": "Hand Cannon · Stasis",
  "Koraxis's Distress": "Grenade Launcher · Strand",
  "Liminal Vigil": "Sidearm · Stasis",
  "Lingering Dread": "Grenade Launcher · Stasis",
  "Long Arm": "Scout Rifle · Arc",
  "Lubrae's Ruin": "Glaive · Solar",
  "Matador 64": "Shotgun · Arc",
  "Midha's Reckoning": "Fusion Rifle · Arc",
  "Mykel's Reverence": "Sidearm · Strand",
  "Naeem's Lance": "Sniper Rifle · Strand",
  "Nation of Beasts": "Hand Cannon · Arc",
  "Necrochasm": "Auto Rifle · Kinetic",
  "Nessa's Oblation": "Shotgun · Void",
  "New Pacific Epitaph": "Grenade Launcher · Stasis",
  "New Purpose": "Pulse Rifle · Stasis",
  "No Survivors": "Submachine Gun · Solar",
  "Non-Denouement": "Combat Bow · Arc",
  "Nullify": "Pulse Rifle · Solar",
  "Omniscient Eye": "Sniper Rifle · Solar",
  "One Thousand Voices": "Fusion Rifle · Solar",
  "Oversoul Edict": "Pulse Rifle · Arc",
  "Posterity": "Hand Cannon · Arc",
  "Praedyth's Revenge": "Sniper Rifle · Kinetic",
  "Prophet of Doom": "Shotgun · Arc",
  "Prosecutor": "Auto Rifle · Arc",
  "Psychopomp": "Grenade Launcher",
  "Qullim's Terminus": "Machine Gun · Stasis",
  "Reckless Oracle": "Auto Rifle · Void",
  "Refusal of the Call": "Glaive · Strand",
  "Relentless": "Pulse Rifle · Strand",
  "Rufus's Fury": "Auto Rifle · Strand",
  "Sacred Provenance": "Pulse Rifle · Kinetic",
  "Smite of Merain": "Pulse Rifle · Kinetic",
  "Song of Ir Yût": "Machine Gun · Arc",
  "Stormchaser": "Linear Fusion Rifle · Arc",
  "Submission": "Submachine Gun · Kinetic",
  "Succession": "Sniper Rifle · Kinetic",
  "Summum Bonum": "Sword · Arc",
  "Swordbreaker": "Shotgun · Strand",
  "Techeun Force": "Fusion Rifle",
  "Terminus Horizon": "Machine Gun · Arc",
  "The Epicurean": "Fusion Rifle · Void",
  "The Navigator": "Trace Rifle · Strand",
  "The Supremacy": "Sniper Rifle",
  "Touch of Malice": "Scout Rifle · Kinetic",
  "Transfiguration": "Scout Rifle",
  "Trustee": "Scout Rifle · Solar",
  "Tyranny of Heaven": "Combat Bow",
  "Unforgiven": "Submachine Gun · Void",
  "Unloved": "Hand Cannon · Strand",
  "Unsworn": "Trace Rifle · Strand",
  "Unvoiced": "Shotgun · Void",
  "Unworthy": "Scout Rifle · Arc",
  "VS Chill Inhibitor": "Grenade Launcher · Stasis",
  "VS Gravitic Arrest": "Fusion Rifle · Void",
  "VS Pyroelectric Propellant": "Auto Rifle · Arc",
  "VS Velocity Baton": "Grenade Launcher · Void",
  "Vengeful Whisper": "Combat Bow · Strand",
  "Vex Mythoclast": "Fusion Rifle · Solar",
  "Vision of Confluence": "Scout Rifle · Solar",
  "Vulpecula": "Hand Cannon",
  "Wilderflight": "Grenade Launcher · Void",
  "Wish-Ender": "Combat Bow · Kinetic",
  "Word of Crota": "Hand Cannon · Void",
  "Xenophage": "Machine Gun · Solar",
  "Zaouli's Bane": "Hand Cannon · Solar",
  "Zealot's Reward": "Fusion Rifle · Void",
};
